import type { Exercise } from '@/types';

export const SAMPLE_EXERCISES: Exercise[] = [
  {
    id: 'ex_001',
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    category_id: '1',
    difficulty: 'intermediate',
    equipment: ['barbell', 'bench'],
    primary_muscle: 'chest',
    secondary_muscles: ['triceps', 'shoulders'],
    instructions: [
      'Lie flat on the bench with feet firmly on the ground.',
      'Grip the bar slightly wider than shoulder width.',
      'Lower the bar to mid-chest with control.',
      'Press the bar up until arms are fully extended.',
      'Keep shoulder blades retracted throughout the movement.',
    ],
    common_mistakes: [
      'Bouncing the bar off the chest',
      'Flaring elbows too wide',
      'Lifting hips off the bench',
      'Uneven bar path',
    ],
    safety_tips: [
      'Always use a spotter for heavy sets',
      'Use safety bars or clips on the barbell',
      'Warm up with lighter weight first',
    ],
    pro_tips: [
      'Drive through your legs for more power',
      'Squeeze the bar to activate more muscle fibers',
      'Pause briefly at the bottom for increased time under tension',
    ],
    calories_per_minute: 8,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_002',
    name: 'Barbell Squat',
    slug: 'barbell-squat',
    category_id: '1',
    difficulty: 'intermediate',
    equipment: ['barbell', 'squat_rack'],
    primary_muscle: 'quadriceps',
    secondary_muscles: ['glutes', 'hamstrings', 'abs'],
    instructions: [
      'Position the bar on your upper traps.',
      'Stand with feet shoulder-width apart, toes slightly out.',
      'Break at the hips and knees simultaneously.',
      'Descend until thighs are parallel to the floor.',
      'Drive through your heels to stand back up.',
    ],
    common_mistakes: [
      'Knees caving inward',
      'Rounding the lower back',
      'Not reaching proper depth',
      'Rising onto toes',
    ],
    safety_tips: [
      'Use safety bars in the squat rack',
      'Keep core braced throughout',
      'Start with bodyweight squats to learn form',
    ],
    pro_tips: [
      'Take a deep breath and brace before each rep',
      'Think about spreading the floor with your feet',
      'Keep your chest up throughout the movement',
    ],
    calories_per_minute: 10,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_003',
    name: 'Deadlift',
    slug: 'deadlift',
    category_id: '1',
    difficulty: 'advanced',
    equipment: ['barbell'],
    primary_muscle: 'back',
    secondary_muscles: ['glutes', 'hamstrings', 'forearms'],
    instructions: [
      'Stand with feet hip-width apart, bar over mid-foot.',
      'Hinge at hips and grip the bar just outside your legs.',
      'Keep back flat and chest up.',
      'Drive through heels and extend hips and knees simultaneously.',
      'Stand tall at the top, then lower with control.',
    ],
    common_mistakes: [
      'Rounding the back',
      'Bar drifting away from body',
      'Jerking the weight off the floor',
      'Hyperextending at the top',
    ],
    safety_tips: [
      'Use a mixed or hook grip for heavy loads',
      'Never round your lower back under load',
      'Use lifting straps only when grip is the limiting factor',
    ],
    pro_tips: [
      'Engage lats by pulling the bar into your shins',
      'Push the floor away rather than pulling the bar up',
      'Reset each rep for heavy sets',
    ],
    calories_per_minute: 11,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_004',
    name: 'Pull-Up',
    slug: 'pull-up',
    category_id: '4',
    difficulty: 'intermediate',
    equipment: ['pull_up_bar', 'bodyweight'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'forearms'],
    instructions: [
      'Hang from the bar with an overhand grip, hands shoulder-width apart.',
      'Engage your lats and pull your chest toward the bar.',
      'Pause at the top with chin above the bar.',
      'Lower with control to full arm extension.',
    ],
    common_mistakes: [
      'Using momentum or kipping',
      'Not achieving full range of motion',
      'Shrugging shoulders at the top',
      'Incomplete lockout at the bottom',
    ],
    safety_tips: [
      'Use a resistance band for assistance if needed',
      'Avoid behind-the-neck pull-ups',
      'Warm up shoulders before heavy sets',
    ],
    pro_tips: [
      'Initiate the pull by depressing your shoulder blades',
      'Squeeze at the top for maximum contraction',
      'Use a false grip for better lat engagement',
    ],
    calories_per_minute: 7,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_005',
    name: 'Overhead Press',
    slug: 'overhead-press',
    category_id: '1',
    difficulty: 'intermediate',
    equipment: ['barbell'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps', 'abs'],
    instructions: [
      'Stand with feet hip-width apart, bar at shoulder height.',
      'Grip the bar just outside shoulder width.',
      'Press the bar overhead until arms are fully locked out.',
      'Lower with control back to shoulder height.',
    ],
    common_mistakes: [
      'Excessive back arch',
      'Pressing the bar in front of the face',
      'Not locking out at the top',
      'Using leg drive (unless push press)',
    ],
    safety_tips: [
      'Keep core tight to protect lower back',
      'Start with lighter weight to learn the movement',
      'Avoid pressing behind the neck',
    ],
    pro_tips: [
      'Push your head through once the bar passes your face',
      'Squeeze glutes to maintain a stable base',
      'Breathe and brace at the bottom of each rep',
    ],
    calories_per_minute: 7,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_006',
    name: 'Dumbbell Bicep Curl',
    slug: 'dumbbell-bicep-curl',
    category_id: '2',
    difficulty: 'beginner',
    equipment: ['dumbbells'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    instructions: [
      'Stand with dumbbells at your sides, palms facing forward.',
      'Keep elbows pinned to your sides.',
      'Curl the weights up toward your shoulders.',
      'Squeeze at the top, then lower with control.',
    ],
    common_mistakes: [
      'Swinging the weights with momentum',
      'Moving elbows forward',
      'Incomplete range of motion',
      'Using too heavy weight',
    ],
    safety_tips: [
      'Control the eccentric portion',
      'Avoid hyperextending elbows at the bottom',
    ],
    pro_tips: [
      'Supinate wrists at the top for peak contraction',
      'Try alternating curls for unilateral focus',
      'Use a slight pause at the bottom to eliminate momentum',
    ],
    calories_per_minute: 4,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_007',
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    category_id: '1',
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells'],
    primary_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'back'],
    instructions: [
      'Hold the bar at hip height with an overhand grip.',
      'Keep a slight bend in the knees.',
      'Hinge at the hips, pushing them back.',
      'Lower until you feel a stretch in your hamstrings.',
      'Drive hips forward to return to standing.',
    ],
    common_mistakes: [
      'Rounding the back',
      'Bending knees too much (turning into a squat)',
      'Not feeling the hamstring stretch',
      'Going too heavy too soon',
    ],
    safety_tips: [
      'Keep the bar close to your legs throughout',
      'Stop if you feel lower back strain',
      'Start with light weight to learn the hip hinge',
    ],
    pro_tips: [
      'Think about closing a car door with your hips',
      'Focus on the hamstring stretch, not depth',
      'Pause at the bottom for increased time under tension',
    ],
    calories_per_minute: 8,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_008',
    name: 'Plank',
    slug: 'plank',
    category_id: '4',
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    primary_muscle: 'abs',
    secondary_muscles: ['obliques', 'shoulders'],
    instructions: [
      'Start in a forearm plank position.',
      'Keep body in a straight line from head to heels.',
      'Engage core and squeeze glutes.',
      'Hold the position for the prescribed time.',
      'Breathe steadily throughout.',
    ],
    common_mistakes: [
      'Hips sagging toward the floor',
      'Hips piking up too high',
      'Holding breath',
      'Looking up instead of down',
    ],
    safety_tips: [
      'Stop if you feel lower back pain',
      'Build up hold time gradually',
    ],
    pro_tips: [
      'Push the floor away with your forearms',
      'Imagine pulling your elbows toward your toes',
      'Progress to side planks for oblique work',
    ],
    calories_per_minute: 5,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_009',
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    category_id: '2',
    difficulty: 'beginner',
    equipment: ['cables'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps'],
    instructions: [
      'Sit at the lat pulldown machine with thighs secured.',
      'Grip the bar wider than shoulder width.',
      'Pull the bar down to upper chest.',
      'Squeeze shoulder blades together at the bottom.',
      'Return to starting position with control.',
    ],
    common_mistakes: [
      'Leaning back too far',
      'Pulling behind the neck',
      'Using momentum',
      'Not achieving full stretch at the top',
    ],
    safety_tips: [
      'Always pull to the front of your chest',
      'Use a weight you can control',
    ],
    pro_tips: [
      'Initiate with your lats, not your arms',
      'Pause at the bottom for peak contraction',
      'Try different grip widths to target different areas',
    ],
    calories_per_minute: 6,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_010',
    name: 'Leg Press',
    slug: 'leg-press',
    category_id: '1',
    difficulty: 'beginner',
    equipment: ['cables'],
    primary_muscle: 'quadriceps',
    secondary_muscles: ['glutes', 'hamstrings'],
    instructions: [
      'Sit in the leg press machine with back flat against the pad.',
      'Place feet shoulder-width apart on the platform.',
      'Lower the weight until knees are at 90 degrees.',
      'Press through your heels to extend legs.',
      'Do not lock out knees at the top.',
    ],
    common_mistakes: [
      'Lowering weight too deep (butt lifting off seat)',
      'Locking knees at the top',
      'Feet placed too high or too low',
      'Using too much weight with poor form',
    ],
    safety_tips: [
      'Never lock your knees completely',
      'Keep lower back pressed against the pad',
      'Use safety stops on the machine',
    ],
    pro_tips: [
      'Vary foot placement to target different muscles',
      'Use single-leg presses for imbalance correction',
      'Control the eccentric for 3 seconds',
    ],
    calories_per_minute: 8,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_011',
    name: 'Tricep Pushdown',
    slug: 'tricep-pushdown',
    category_id: '2',
    difficulty: 'beginner',
    equipment: ['cables'],
    primary_muscle: 'triceps',
    secondary_muscles: [],
    instructions: [
      'Stand facing the cable machine with rope or bar attachment.',
      'Keep elbows pinned to your sides.',
      'Push the attachment down until arms are fully extended.',
      'Squeeze triceps at the bottom.',
      'Return with control to starting position.',
    ],
    common_mistakes: [
      'Moving elbows away from body',
      'Using shoulders to push down',
      'Incomplete extension at the bottom',
      'Leaning over the bar',
    ],
    safety_tips: [
      'Use a weight you can control through full ROM',
      'Keep wrists neutral',
    ],
    pro_tips: [
      'Try rope attachment for better peak contraction',
      'Pause at the bottom for 1 second',
      'Use drop sets for advanced hypertrophy',
    ],
    calories_per_minute: 4,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ex_012',
    name: 'Hip Thrust',
    slug: 'hip-thrust',
    category_id: '1',
    difficulty: 'intermediate',
    equipment: ['barbell', 'bench'],
    primary_muscle: 'glutes',
    secondary_muscles: ['hamstrings'],
    instructions: [
      'Sit on the floor with upper back against a bench.',
      'Roll a barbell over your hips (use a pad for comfort).',
      'Drive through your heels to lift hips up.',
      'Squeeze glutes hard at the top.',
      'Lower with control and repeat.',
    ],
    common_mistakes: [
      'Hyperextending the lower back',
      'Not achieving full hip extension',
      'Pushing through toes instead of heels',
      'Looking up excessively',
    ],
    safety_tips: [
      'Use a barbell pad to protect hips',
      'Start with bodyweight to learn the movement',
    ],
    pro_tips: [
      'Pause at the top for 2 seconds',
      'Keep chin tucked throughout',
      'Try single-leg variations for unilateral work',
    ],
    calories_per_minute: 7,
    video_url: null,
    model_url: null,
    thumbnail_url: null,
    created_at: new Date().toISOString(),
  },
];
